### ISSUE TITLE
Field compileEnumImpl overrides parent class with different or incomplete type

### ISSUE THREAD

**Issue by neimanpinchas** [RobertBorghese/reflaxe#2]
Hi i am having issues with compiling the reflexe testcompiler, was the Test not updated with the compiler? or I am missing something fundemetal;
  root@laptop:/media/hd/haxego/reflaxe-main/test# haxe Test.hxml
  TestCompiler.hx:62: characters 18-33 : Field compileEnumImpl overrides parent class with different or incomplete type
  ../src/reflaxe/BaseCompiler.hx:279: characters 27-42 : ... Base field is defined here
  TestCompiler.hx:62: characters 18-33 : ... error: Map<String, haxe.macro.EnumField> should be reflaxe.EnumOptions
  TestCompiler.hx:62: characters 18-33 : ... have: (..., reflaxe.EnumOptions) -> ...
  TestCompiler.hx:62: characters 18-33 : ... want: (..., Map<..., ...>) -> ...
  TestCompiler.hx:18: characters 7-19 : This class extends abstract class reflaxe.BaseCompiler but doesn't implement the following method
  TestCompiler.hx:18: characters 7-19 : Implement it or make TestCompiler abstract as well
  ../src/reflaxe/BaseCompiler.hx:279: characters 27-42 : ... compileEnumImpl(enumType:haxe.macro.EnumType, options:reflaxe.EnumOptions)

**Comment by RobertBorghese** [comment]
Thank you for the report! Fixed with f7f28b33156f99875f78fe2b30132a8b8144c88b!

I'd also recommend re-downloading the `test/` directory, as I've gone ahead and added a README + documented the code in `TestCompiler.hx`, so it should work better as a project template. Thanks for your support, and please let me know if you encounter anything else!
